import io
import os
import re
from pathlib import Path

import openpyxl
import pdfplumber
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from openpyxl import Workbook

BASE_DIR = Path(__file__).resolve().parent
TEMPLATES_DIR = BASE_DIR / "templates"
OUTPUTS_DIR = BASE_DIR / "outputs"

app = FastAPI(title="VTS Panjang PDF Extractor")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def ensure_directories():
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)


def create_template_kapal(path: Path):
    wb = Workbook()
    ws = wb.active
    ws.title = "Data Kapal"
    ws["A3"] = "TEMPLATE DATA KAPAL"
    ws["A5"] = "NAMA KAPAL"
    ws["B5"] = ""
    ws["C5"] = ""
    ws["A6"] = "NOMOR KAPAL"
    ws["A8"] = "Generated by VTS Panjang PDF Extractor"
    wb.save(path)


def create_template_cuaca(path: Path):
    wb = Workbook()
    ws = wb.active
    ws.title = "Data Cuaca"
    ws["A3"] = "TEMPLATE DATA CUACA"
    ws["A4"] = "KECEPATAN ANGIN"
    ws["B4"] = ""
    ws["A6"] = "Generated by VTS Panjang PDF Extractor"
    wb.save(path)


def ensure_templates():
    kapal_path = TEMPLATES_DIR / "template_kapal.xlsx"
    cuaca_path = TEMPLATES_DIR / "template_cuaca.xlsx"

    if not kapal_path.exists():
        create_template_kapal(kapal_path)

    if not cuaca_path.exists():
        create_template_cuaca(cuaca_path)


def extract_field(text: str, labels: list[str]) -> str:
    for label in labels:
        escaped = re.escape(label)
        pattern = re.compile(rf"{escaped}\s*[:\-]?\s*(.+)", re.IGNORECASE)
        match = pattern.search(text)
        if match:
            value = match.group(1).strip()
            if value:
                return value.split("\n")[0].strip()

    for line in text.splitlines():
        upper = line.upper()
        for label in labels:
            label_upper = label.upper()
            if label_upper in upper:
                remainder = line[upper.index(label_upper) + len(label_upper) :].strip(" :\t-\u2013")
                if remainder:
                    return remainder.strip()

    return ""


@app.on_event("startup")
def startup_event():
    ensure_directories()
    ensure_templates()


@app.post("/api/convert")
async def convert_pdf(upload_file: UploadFile = File(...)):
    if upload_file.content_type != "application/pdf":
        raise HTTPException(status_code=422, detail="Format dokumen ditolak! Hanya file PDF yang diterima.")

    file_bytes = await upload_file.read()
    if not file_bytes:
        raise HTTPException(status_code=422, detail="File PDF kosong atau tidak dapat dibaca.")

    try:
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            if not pdf.pages:
                raise HTTPException(status_code=422, detail="PDF tidak memiliki halaman.")
            first_page_text = pdf.pages[0].extract_text() or ""
    except Exception:
        raise HTTPException(status_code=422, detail="Gagal membaca PDF. Pastikan file valid.")

    normalized_text = first_page_text.upper()
    is_a2 = "DATA OPERATOR - KAPAL" in normalized_text or "CREW LIST" in normalized_text
    is_a1 = "LAPORAN METEOROLOGI" in normalized_text or "CUACA" in normalized_text

    if is_a2:
        template_name = "template_kapal.xlsx"
        output_filename = "Data 16-17.xlsx"
        sheet_keys = {
            "nama_kapal": ["NAMA KAPAL"],
            "nomor_kapal": ["NOMOR KAPAL", "NO KAPAL", "NOMOR KAPAL"]
        }
    elif is_a1:
        template_name = "template_cuaca.xlsx"
        output_filename = "Data Cuaca.xlsx"
        sheet_keys = {"kecepatan_angin": ["KECEPATAN ANGIN", "KECEPATAN ANGIN "]}
    else:
        raise HTTPException(
            status_code=422,
            detail="Format dokumen ditolak! PDF tidak sesuai dengan template Data Kapal (A2) atau Data Cuaca (A1).",
        )

    template_path = TEMPLATES_DIR / template_name
    if not template_path.exists():
        ensure_templates()

    workbook = openpyxl.load_workbook(template_path)
    worksheet = workbook.active

    if is_a2:
        nama_kapal = extract_field(first_page_text, sheet_keys["nama_kapal"]) or ""
        nomor_kapal = extract_field(first_page_text, sheet_keys["nomor_kapal"]) or ""
        worksheet["B5"] = nama_kapal or "N/A"
        worksheet["C5"] = nomor_kapal or "N/A"
    else:
        kecepatan_angin = extract_field(first_page_text, sheet_keys["kecepatan_angin"]) or ""
        worksheet["B4"] = kecepatan_angin or "N/A"

    output_path = OUTPUTS_DIR / output_filename
    workbook.save(output_path)

    return FileResponse(
        path=output_path,
        filename=output_filename,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )
