import io
import os
import re
from pathlib import Path

import openpyxl
import pdfplumber
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from openpyxl import Workbook

BASE_DIR = Path(__file__).resolve().parent
TEMPLATES_DIR = BASE_DIR / "templates"
OUTPUTS_DIR = BASE_DIR / "outputs"

app = FastAPI(title="VTS Panjang PDF Extractor")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def ensure_directories():
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)


def create_template_kapal(path: Path):
    wb = Workbook()
    ws = wb.active
    ws.title = "Data Kapal"
    ws["A3"] = "TEMPLATE DATA KAPAL"
    ws["A5"] = "NAMA KAPAL"
    ws["B5"] = ""
    ws["C5"] = ""
    ws["A6"] = "NOMOR KAPAL"
    ws["A8"] = "Generated by VTS Panjang PDF Extractor"
    wb.save(path)


def create_template_cuaca(path: Path):
    wb = Workbook()
    ws = wb.active
    ws.title = "Data Cuaca"
    ws["A3"] = "TEMPLATE DATA CUACA"
    ws["A4"] = "KECEPATAN ANGIN"
    ws["B4"] = ""
    ws["A6"] = "Generated by VTS Panjang PDF Extractor"
    wb.save(path)


def ensure_templates():
    kapal_path = TEMPLATES_DIR / "template_kapal.xlsx"
    cuaca_path = TEMPLATES_DIR / "template_cuaca.xlsx"

    if not kapal_path.exists():
        create_template_kapal(kapal_path)

    if not cuaca_path.exists():
        create_template_cuaca(cuaca_path)


def normalize_text(text: str) -> str:
    """Normalize text: lowercase, remove extra spaces/newlines."""
    text = text.lower()
    # Replace multiple spaces/tabs/newlines with single space
    text = re.sub(r'\s+', ' ', text)
    return text.strip()


def extract_field(text: str, labels: list[str]) -> str:
    """Extract field value from text with flexible matching."""
    for label in labels:
        # Normalize both label and text for matching
        normalized_label = normalize_text(label)
        normalized_text = normalize_text(text)
        
        # Try exact pattern match with flexible spacing
        escaped = re.escape(normalized_label)
        pattern = re.compile(rf"{escaped}\s*[:\-]?\s*(.+)")
        match = pattern.search(normalized_text)
        if match:
            value = match.group(1).strip()
            if value:
                return value.split(" ")[0].strip()

    # Fallback: line by line search
    for line in text.splitlines():
        normalized_line = normalize_text(line)
        for label in labels:
            normalized_label = normalize_text(label)
            if normalized_label in normalized_line:
                # Extract remainder after label
                idx = normalized_line.index(normalized_label) + len(normalized_label)
                remainder = normalized_line[idx:].strip(" :\t-–")
                if remainder:
                    return remainder.strip()

    return ""


def find_template_type(pdf_text: str) -> str:
    """Detect PDF template type by searching keywords across all text."""
    normalized = normalize_text(pdf_text)
    
    # Keywords for A2 (Kapal)
    a2_keywords = ["data operator kapal", "crew list"]
    # Keywords for A1 (Cuaca)
    a1_keywords = ["laporan meteorologi", "cuaca"]
    
    # Check A2 keywords
    for keyword in a2_keywords:
        if keyword in normalized:
            return "A2"
    
    # Check A1 keywords
    for keyword in a1_keywords:
        if keyword in normalized:
            return "A1"
    
    return None


@app.on_event("startup")
def startup_event():
    ensure_directories()
    ensure_templates()


@app.post("/api/convert")
async def convert_pdf(upload_file: UploadFile = File(...)):
    if upload_file.content_type != "application/pdf":
        raise HTTPException(status_code=422, detail="Format dokumen ditolak! Hanya file PDF yang diterima.")

    file_bytes = await upload_file.read()
    if not file_bytes:
        raise HTTPException(status_code=422, detail="File PDF kosong atau tidak dapat dibaca.")

    try:
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            if not pdf.pages:
                raise HTTPException(status_code=422, detail="PDF tidak memiliki halaman.")
            
            # Extract text from all pages
            full_text = ""
            for page in pdf.pages:
                page_text = page.extract_text() or ""
                full_text += page_text + "\n"
    except Exception:
        raise HTTPException(status_code=422, detail="Gagal membaca PDF. Pastikan file valid.")

    # Detect template type with flexible matching
    template_type = find_template_type(full_text)
    
    if template_type == "A2":
        template_name = "template_kapal.xlsx"
        output_filename = "Data 16-17.xlsx"
        sheet_keys = {
            "nama_kapal": ["NAMA KAPAL"],
            "nomor_kapal": ["NOMOR KAPAL", "NO KAPAL"]
        }
    elif template_type == "A1":
        template_name = "template_cuaca.xlsx"
        output_filename = "Data Cuaca.xlsx"
        sheet_keys = {"kecepatan_angin": ["KECEPATAN ANGIN"]}
    else:
        raise HTTPException(
            status_code=422,
            detail="Format dokumen ditolak! PDF tidak sesuai dengan template Data Kapal (A2) atau Data Cuaca (A1).",
        )

    template_path = TEMPLATES_DIR / template_name
    if not template_path.exists():
        ensure_templates()

    workbook = openpyxl.load_workbook(template_path)
    worksheet = workbook.active

    if template_type == "A2":
        nama_kapal = extract_field(full_text, sheet_keys["nama_kapal"]) or ""
        nomor_kapal = extract_field(full_text, sheet_keys["nomor_kapal"]) or ""
        worksheet["B5"] = nama_kapal or "N/A"
        worksheet["C5"] = nomor_kapal or "N/A"
    else:
        kecepatan_angin = extract_field(full_text, sheet_keys["kecepatan_angin"]) or ""
        worksheet["B4"] = kecepatan_angin or "N/A"

    output_path = OUTPUTS_DIR / output_filename
    workbook.save(output_path)

    return FileResponse(
        path=output_path,
        filename=output_filename,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )
